language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository

cache:
  directories:
    - $HOME/.gradle
