language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository

after_success:
    - .buildscript/deploy_snapshot.sh

cache:
  directories:
    - $HOME/.gradle

branches:
  only:
  - master

env:
  global:
    - secure: RcG2qYr5r6qU7aIrdFaqSvrCC7HmqDdBqyACGfRz184RW7/9TOXvKTRTkX+edHMbc96ItTh2lH4A/r5T7pUCtCoy9sprMHqN24R11PJgfuoAuFkOycOXhp/gXf3wqVBjcLJ7HC+aIZB68j0E8cgU/sayKltrd6nEgv9gd94S2sZ65ObCpt3KASplh2Xe47ORwmLuEVePiPXiQ6RyETouHoPqVn8Kz36jPzZ6lyPASYU5qWRk1N/5NNB8bx1EvUk8g/IueH7B0S6GWwuFuSqrAx+bDbOimemc2tgMjG/y90PiPGupX+ZJiqpmOE0KwQC23wd06ILmf61PkljS5hPyAc7asQQQ/1LaWobkEklenbmyVvilWTWKVGrRYer5sdu47lnZwvLWqLo1lS3R1sOEc3SGy6OBg8NZMPqNaT8axpLi8kE9PA5gS3sJNQtCQzFgGkBwzdmp12afGGW3is5ZKl5B0nhrtFGBuem8y/DPsPTmK5j+zAtS1/4JoGuLDjfX8cjrZ2KcPKO89aWjg+WPZaC6ebV1+WB7RFo6bT0uQvxjKm5PDBEMZtQKY+dMPvEDzCNB7LAG5X0za/1HDwEPk2Xi1ntONtEj1LP9SG+RRvZ124+erdGtq4yn6A7X2T9dtkp8uuJOAmmE4RSlxe8SLwtK4x3aOKuok6hkkLpMSYo=
    - secure: Y9bilWGQClO0yhIZ8YRiasU0AId0cLws4jLxrtUmJLP/Pp0xZ2oWdohGx6MeaZlJf24uE+yyy+enYIZnJgOdmodS+QaLa3035wnibyuLGp2mtSACcsiOh47JgPyey6P7p4hQlT/FwX3y243vPPUAgkD05yukRL/MF3XGVL9SFueGqnBR0Mrs7vlVAAO5tRFb6K3C8vcTaYJrtghMMDhx1K+diFA29e25UtFjtbwgVydAQ6bP4Me+OcTf/TgpNUSIEVEYU4aD1+fW523lEi9O1JYDjxiWeCsrgSF09ugA5uyr2GnkoYCyhvl8FYz8u/B0O/N/EgG2WjafHiOOMgKI/O5cKijNowa3i+Z0g6huioPkyCTlPmcyExZwsU2cGR9KFS45Lqkz7lTXxW5dmMQQhSmYyyuXnqKrGMqKPvYdE0cZJ2hH7ssBLjr+Xhjy+352YRoNEUs3JieyKkrk/ErZ08W5QNuDS6TEYF8dgHMmkeE7QMhlBFDIbab3IikfLxwYhoEmd/kKLb/P9MLzowAw6WrErsTi9zrHcBD4vQjMWwhBU2gPEaQsTh3AJEoNsjlyVmhddCVL8mlqedAM+V+6LWTAdATT3mhr8SOO9lOCzZ2qSJ34U7wE5OzWmXQ2j+t73fvT6wP+d/lbvjG/7Co4BG3O23zg8/sPbCOVOpS/NT8=
